// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("awss3putobject")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awss3putobjectreceiver"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
