// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("s3")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/s3receiver"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
